import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";

const ubuntu = Fira_Code({
  weight: "500",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className} dark antialiased`}>
        <div className="flex justify-center">
          <div className="w-10/12 p-16">{children}</div>
        </div>
      </body>
    </html>
  );
}
